In [52]:
Pkg.add("Images")
Pkg.add("DataFrames")
Pkg.add("ImageMagick")
Pkg.add("CSV")
Pkg.add("DecisionTree")
using Images
using DataFrames
using CSV
using DecisionTree
println("Loaded")


INFO: Package Images is already installed
INFO: Package DataFrames is already installed
INFO: Package ImageMagick is already installed
INFO: Package CSV is already installed
INFO: Package DecisionTree is already installed
INFO: Precompiling module DecisionTree.


Loaded


In [27]:
function read_data(typeData, labelsInfo, imageSize, path)
    # Reference: Kaggle First Steps with Julia - https://www.kaggle.com/c/street-view-getting-started-with-julia#julia-tutorial 

    # initialize matrix to hold the image
    x::Array{Float32,2} = zeros(size(labelsInfo, 1), imageSize)

    for (index, idImage) in enumerate(labelsInfo[:ID])
        # read the image from file
        nameFile = "$(path)/$(typeData)Resized/$(idImage).Bmp"
        img = Images.load(nameFile)

        # convert image to floats
        temp = rawview(channelview(float32(img))) # sc scales the floats to between 0-1

        # if colour, to have a consistent representation, we convert to grayscale
        if ndims(temp) == 3 #  ndims returns the number of dimensions of array
            temp = mean(temp, 1) # average across the first dimension
        end

        # transform image to vector
        x[index, :] = reshape(temp,1,imageSize)::Array{Float32,2}
    end

    return x # x is a matrix of values, ith row containing a vector representing the
            # pixel values of the ith image
end

read_data (generic function with 1 method)

In [6]:
# path to data 
path = "./data"
imageSize = 400 # 20 * 20 pixel data values

400

In [17]:

# load training data
labelsInfoTrain = CSV.read("$(path)/trainLabels.csv") # trainLabels contains extra data

labelsInfoTest = CSV.read("$(path)/sampleSubmission.csv") # testLabels contains testing metadata


6220×2 DataFrames.DataFrame
│ Row  │ ID    │ Class │
├──────┼───────┼───────┤
│ 1    │ 6284  │ A     │
│ 2    │ 6285  │ A     │
│ 3    │ 6286  │ A     │
│ 4    │ 6287  │ A     │
│ 5    │ 6288  │ A     │
│ 6    │ 6289  │ A     │
│ 7    │ 6290  │ A     │
│ 8    │ 6291  │ A     │
│ 9    │ 6292  │ A     │
│ 10   │ 6293  │ A     │
│ 11   │ 6294  │ A     │
⋮
│ 6209 │ 12492 │ A     │
│ 6210 │ 12493 │ A     │
│ 6211 │ 12494 │ A     │
│ 6212 │ 12495 │ A     │
│ 6213 │ 12496 │ A     │
│ 6214 │ 12497 │ A     │
│ 6215 │ 12498 │ A     │
│ 6216 │ 12499 │ A     │
│ 6217 │ 12500 │ A     │
│ 6218 │ 12501 │ A     │
│ 6219 │ 12502 │ A     │
│ 6220 │ 12503 │ A     │

In [28]:
xTrain = read_data("train", labelsInfoTrain, imageSize, path)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] float32(::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at ./deprecated.jl:57
 [3] read_data(::String, ::DataFrames.DataFrame, ::Int64, ::String) at ./In[27]:13
 [4] include_string(::String, ::String) at ./loading.jl:522
 [5] include_string(::Module, ::String, ::String) at /home/gopiandcode/.julia/v0.6/Compat/src/Compat.jl:71
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/gopiandcode/.julia/v0.6/IJulia/src/execute_request.jl:158
 [7] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/gopiandcode/.julia/v0.6/Compat/src/Compat.jl:385
 [8] eventloop(::ZMQ.Socket) at /home/gopiandcode/.julia/v0.6/IJulia/src/eventloop.jl:8
 [9] (::IJulia.##14#17)() at ./task.jl:335
while loading In[28], in expression starting on line 1


6283×400 Array{Float32,2}:
 0.267974   0.275817   0.27451    …  0.275817   0.278431   0.298039 
 0.464052   0.462745   0.464052      0.457516   0.457516   0.457516 
 0.254902   0.269281   0.249673      0.28366    0.266667   0.267974 
 0.295425   0.304575   0.40915       0.437909   0.495425   0.508497 
 0.0784314  0.0666667  0.0653595     0.0836601  0.0888889  0.0705882
 0.460131   0.457516   0.460131   …  0.47451    0.466667   0.460131 
 0.337255   0.339869   0.332026      0.34902    0.332026   0.334641 
 0.243137   0.203922   0.231373      0.27451    0.287582   0.254902 
 0.235294   0.227451   0.226144      0.214379   0.235294   0.223529 
 0.788235   0.822222   0.853595      0.947713   0.94902    0.952941 
 0.330719   0.330719   0.312418   …  0.419608   0.416993   0.407843 
 0.301961   0.304575   0.308497      0.343791   0.279739   0.296732 
 0.243137   0.67451    0.743791      0.2        0.138562   0.128105 
 ⋮                                ⋱                                 
 0.6196

In [30]:
xTest = read_data("test", labelsInfoTest, imageSize, path)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] float32(::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},2}) at ./deprecated.jl:57
 [3] read_data(::String, ::DataFrames.DataFrame, ::Int64, ::String) at ./In[27]:13
 [4] include_string(::String, ::String) at ./loading.jl:522
 [5] include_string(::Module, ::String, ::String) at /home/gopiandcode/.julia/v0.6/Compat/src/Compat.jl:71
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/gopiandcode/.julia/v0.6/IJulia/src/execute_request.jl:158
 [7] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/gopiandcode/.julia/v0.6/Compat/src/Compat.jl:385
 [8] eventloop(::ZMQ.Socket) at /home/gopiandcode/.julia/v0.6/IJulia/src/eventloop.jl:8
 [9] (::IJulia.##14#17)() at ./task.jl:335
while loading In[30], in expression starting on line 1


6220×400 Array{Float32,2}:
 0.470588  0.453595  0.457516   0.458824   …  0.890196  0.639216  0.490196
 0.284967  0.279739  0.282353   0.294118      0.39085   0.326797  0.301961
 0.115033  0.122876  0.0993464  0.0941177     0.185621  0.111111  0.105882
 0.586928  0.586928  0.575163   0.584314      0.593464  0.568627  0.581699
 0.496732  0.48366   0.501961   0.518954      0.156863  0.440523  0.541176
 0.550327  0.550327  0.542484   0.542484   …  0.320261  0.300654  0.495425
 0.156863  0.160784  0.14902    0.152941      0.150327  0.172549  0.169935
 0.752941  0.752941  0.762092   0.780392      0.781699  0.786928  0.769935
 0.708497  0.712418  0.708497   0.687582      0.751634  0.730719  0.698039
 0.886275  0.879739  0.869281   0.845752      0.203922  0.329412  0.922876
 0.245752  0.321569  0.392157   0.397386   …  0.257516  0.267974  0.271895
 0.738562  0.781699  0.783007   0.779085      0.784314  0.784314  0.781699
 0.405229  0.401307  0.414379   0.427451      0.405229  0.397386  0.40522

In [42]:
yTrain = map(x -> x[1], labelsInfoTrain[:Class])

6283-element CategoricalArrays.CategoricalArray{Any,1,UInt32}:
 'n'
 '8'
 'T'
 'I'
 'R'
 'W'
 'L'
 'l'
 'K'
 'G'
 'A'
 'A'
 'C'
 ⋮  
 't'
 'S'
 'e'
 'l'
 'O'
 'R'
 'L'
 'N'
 'I'
 'P'
 'N'
 'R'

In [54]:
ytrain = map(x -> Int(x), Array(decompress(yTrain)))

6283-element Array{Int64,1}:
 110
  56
  84
  73
  82
  87
  76
 108
  75
  71
  65
  65
  67
   ⋮
 116
  83
 101
 108
  79
  82
  76
  78
  73
  80
  78
  82

In [58]:
# train random forest with
# 20 features at random splits
# 50 trees
# 1.0 subsamples 
# need to look up exactly how the random forest algorithm works 
model = build_forest(Array(yTrain), Array(xTrain), 20, 50, 1.0)

Ensemble of Decision Trees
Trees:      50
Avg Leaves: 2229.12
Avg Depth:  19.48

In [59]:
predTest = apply_forest(model, xTest)


6220-element Array{Any,1}:
 'H'
 'E'
 'A'
 'O'
 'S'
 'i'
 '0'
 'a'
 'a'
 'H'
 'N'
 'A'
 'N'
 ⋮  
 'A'
 'A'
 'a'
 'c'
 'E'
 'A'
 'V'
 'o'
 'D'
 'A'
 'R'
 'M'

In [62]:
labelsInfoTest[:Class] = map(x -> Char(x), predTest)

6220-element Array{Char,1}:
 'H'
 'E'
 'A'
 'O'
 'S'
 'i'
 '0'
 'a'
 'a'
 'H'
 'N'
 'A'
 'N'
 ⋮  
 'A'
 'A'
 'a'
 'c'
 'E'
 'A'
 'V'
 'o'
 'D'
 'A'
 'R'
 'M'

In [74]:
CSV.write("$(path)/juliaSubmission.csv", labelsInfoTest; header=true)

CSV.Sink{Void,DataType}(    CSV.Options:
        delim: ','
        quotechar: '"'
        escapechar: '\\'
        null: ""
        dateformat: nothing
        decimal: '.'
        truestring: 'true'
        falsestring: 'false', IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1), "./data/juliaSubmission.csv", 9, true, String["ID", "Class"], 2, false, Val{false})